include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    prefer_final_locals: true
    sort_constructors_first: true
    use_super_parameters: true
